import {
  DetailsGrid,
  NameValueTable,
  SectionBox,
} from '@kinvolk/headlamp-plugin/lib/components/common';
import { Chip, Box, Typography } from '@mui/material';
import { useParams } from 'react-router-dom';
import { KafkaUser, ACLRule } from '../../resources/kafkauser';
import { ACLVisualization } from './ACLVisualization';

export function UserDetail() {
  const { name, namespace } = useParams<{ name: string; namespace: string }>();

  return (
    <DetailsGrid
      resourceType={KafkaUser}
      name={name}
      namespace={namespace}
      withEvents
      extraInfo={item =>
        item && [
          {
            name: 'Status',
            value: item.ready ? 'Ready' : 'Not Ready',
          },
          {
            name: 'Cluster',
            value: item.clusterName,
          },
          {
            name: 'Authentication',
            value: (
              <Chip
                label={item.authenticationType}
                color={
                  item.authenticationType === 'tls' || item.authenticationType === 'tls-external'
                    ? 'primary'
                    : item.authenticationType === 'scram-sha-512'
                    ? 'secondary'
                    : 'default'
                }
                size="small"
                variant="outlined"
              />
            ),
          },
          {
            name: 'Authorization',
            value: (
              <Chip
                label={item.authorizationType}
                color={item.authorizationType === 'simple' ? 'success' : 'default'}
                size="small"
                variant="outlined"
              />
            ),
          },
          {
            name: 'ACL Rules',
            value: item.aclCount.toString(),
          },
        ]
      }
      extraSections={item =>
        item && [
          {
            id: 'Authentication',
            section: item.spec?.authentication && (
              <SectionBox title="Authentication Details">
                <NameValueTable
                  rows={[
                    {
                      name: 'Type',
                      value: item.spec.authentication.type,
                    },
                    {
                      name: 'Description',
                      value:
                        item.spec.authentication.type === 'tls'
                          ? 'Mutual TLS authentication with user certificate generated by User Operator'
                          : item.spec.authentication.type === 'tls-external'
                          ? 'Mutual TLS authentication with user certificate generated outside User Operator'
                          : item.spec.authentication.type === 'scram-sha-512'
                          ? 'SASL SCRAM-SHA-512 authentication with username/password'
                          : 'No authentication configured',
                    },
                    ...(item.spec.authentication.password?.valueFrom
                      ? [
                          {
                            name: 'Password Source',
                            value: `Secret: ${item.spec.authentication.password.valueFrom.secretKeyRef.name}/${item.spec.authentication.password.valueFrom.secretKeyRef.key}`,
                          },
                        ]
                      : []),
                    ...(item.status?.username
                      ? [
                          {
                            name: 'Username',
                            value: item.status.username,
                          },
                        ]
                      : []),
                  ]}
                />
              </SectionBox>
            ),
          },
          {
            id: 'ACLs',
            section: item.acls && item.acls.length > 0 && (
              <SectionBox title="Access Control Lists (ACLs)">
                <ACLVisualization acls={item.acls} />
              </SectionBox>
            ),
          },
          {
            id: 'Quotas',
            section: item.quotas && (
              <SectionBox title="Quotas">
                <NameValueTable
                  rows={[
                    ...(item.quotas.producerByteRate !== undefined
                      ? [
                          {
                            name: 'Producer Byte Rate',
                            value: `${item.quotas.producerByteRate} bytes/sec`,
                          },
                        ]
                      : []),
                    ...(item.quotas.consumerByteRate !== undefined
                      ? [
                          {
                            name: 'Consumer Byte Rate',
                            value: `${item.quotas.consumerByteRate} bytes/sec`,
                          },
                        ]
                      : []),
                    ...(item.quotas.requestPercentage !== undefined
                      ? [
                          {
                            name: 'Request Percentage',
                            value: `${item.quotas.requestPercentage}%`,
                          },
                        ]
                      : []),
                    ...(item.quotas.controllerMutationRate !== undefined
                      ? [
                          {
                            name: 'Controller Mutation Rate',
                            value: `${item.quotas.controllerMutationRate} mutations/sec`,
                          },
                        ]
                      : []),
                  ]}
                />
              </SectionBox>
            ),
          },
          {
            id: 'Status',
            section: item.status && (
              <SectionBox title="Status">
                {item.status.conditions && item.status.conditions.length > 0 ? (
                  <NameValueTable
                    rows={item.status.conditions.map(condition => ({
                      name: condition.type,
                      value: (
                        <div>
                          <div>Status: {condition.status}</div>
                          {condition.reason && <div>Reason: {condition.reason}</div>}
                          {condition.message && <div>Message: {condition.message}</div>}
                          {condition.lastTransitionTime && (
                            <div>Last Transition: {condition.lastTransitionTime}</div>
                          )}
                        </div>
                      ),
                    }))}
                  />
                ) : (
                  <div>No status conditions available</div>
                )}
              </SectionBox>
            ),
          },
        ]
      }
    />
  );
}
